imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    metador:
        logo: %metador.logo%
        favicon: %metador.favicon%

        templates:
            form: %metador.templates.form%
            base: %metador.templates.base%
            main: %metador.templates.main%
            login: %metador.templates.login%

        gdi_de:
            url: %metador.gdi.de.url%
            user: %metador.gdi.de.user%
            password: %metador.gdi.de.password%

        proxy:
            host: %metador.proxy.host%
            port: %metador.proxy.port%

        export:
            path: %metador.export.path%

        xmlimport:
            schema: %metador.xmlimport.schema%

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        cookie_path: "%cookie_path%"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        version: 2.0.4.0


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database.driver%
                host:     %database.host%
                port:     %database.port%
                dbname:   %database.name%
                path:     %database.path%
                user:     %database.user%
                password: %database.password%
                charset:  %database.charset%
            external:
                driver:   %external.database.driver%
                host:     %external.database.host%
                port:     %external.database.port%
                dbname:   %external.database.name%
                path:     %external.database.path%
                user:     %external.database.user%
                password: %external.database.password%
                charset:  %external.database.charset%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    WhereGroupMetadorBundle: ~
                    WhereGroupUserBundle: ~
            # external:
            #     connection: external
            #     mappings: 
            #         WhereGroupMapbender3Bundle: ~
