where_group_core:
    resource: "@WhereGroupCoreBundle/Controller/"
    type:     annotation

where_group_user:
    resource: "@WhereGroupUserBundle/Controller/"
    type:     annotation

where_group_theme:
    resource: "@WhereGroupThemeBundle/Controller/"
    type:     annotation
