_metador:
    pattern:   /
    defaults:  { _controller: WhereGroupCoreBundle:Dashboard:index }

where_group_core:
    resource: "@WhereGroupCoreBundle/Controller/"
    type:     annotation

where_group_user:
    resource: "@WhereGroupUserBundle/Controller/"
    type:     annotation

where_group_metador:
    resource: "@WhereGroupMetadorBundle/Controller/"
    type:     annotation

where_group_search:
    resource: "@WhereGroupSearchBundle/Controller/"
    type:     annotation
