parameters:
    metador.user: ~
    metador.logo: "bundles/wheregroupmetador/img/logo3.png"
    metador.favicon: "bundles/wheregroupmetador/img/favicon.png"
    metador.templates.form: "WhereGroupMetadorBundle"
    metador.templates.base: "::boilerplate.html.twig"
    metador.templates.main: "WhereGroupMetadorBundle:Design:main.html.twig"
    metador.templates.login: ":Design:login.html.twig"
    metador.hits: 20
    metador.gdi.de.url: "https://testsuite.gdi-de.org/gdi/download?id=wsdl"
    metador.gdi.de.user: ~
    metador.gdi.de.password: ~
    metador.gdi.de.testlevel:
        # - PASS
        # - INHERITED_FAILURE
        - FAIL
    metador.proxy.host: ~
    metador.proxy.port: ~
    metador.export.path: ~
    metador.xmlimport.schema:
        - "%kernel.root_dir%/../src/WhereGroup/MetadorBundle/Resources/config/xmlimport.json"
    metador.wmsimport.path: "%kernel.root_dir%/../src/WhereGroup/MetadorBundle/Resources/config/"
    metador.search.templates: "WhereGroupSearchBundle"
