parameters:
    metador.logo: "bundles/wheregroupmetador/img/logo3.png"
    
    metador.templates.form: "WhereGroupMetadorBundle"
    metador.templates.xml: "WhereGroupMetadorBundle"

    metador.gdi.de.url: "http://testsuite.gdi-de.org:80/gdi/download?id=wsdl"
    metador.gdi.de.user: ~
    metador.gdi.de.password: ~

    metador.proxy.host: ~
    metador.proxy.port: ~

    metador.export.path: ~