parameters:
    metador.user: ~
    metador.hits: 20
    metador.gdi.de.url: "https://testsuite.gdi-de.org/gdi/download?id=wsdl"
    metador.gdi.de.user: ~
    metador.gdi.de.password: ~
    metador.gdi.de.testlevel:
        # - PASS
        # - INHERITED_FAILURE
        - FAIL
    metador.proxy.host: ~
    metador.proxy.port: ~
    metador.export.path: ~
    metador.xmlimport.schema:
        - "%kernel.root_dir%/../src/WhereGroup/CoreBundle/Resources/config/xmlimport.json"
    metador.wmsimport.path: "%kernel.root_dir%/../src/WhereGroup/CoreBundle/Resources/config/"
    metador.search.templates: "WhereGroupSearchBundle"
